Repository data-eden/data-eden, pull requests merged in 2022-08, with the labels that each got.

#31 bug: adds prepublish to make sure published packages have dist and d.ts file
  CHANGELOG.md
  package.json
Labels: bug

#32 Add `CHANGELOG.md` to `.prettierignore`
  .prettierignore
Labels: internal

#33 Add license field to published package.json's
  packages/athena/package.json
  packages/cache/package.json
  packages/network/package.json
Labels: documentation

#34 feat: export types from fetch to utilize in external middlewares
  packages/network/src/index.ts
Labels: bug

#37 Update vite and vitest to latest
  package-lock.json
  package.json
Labels: internal

#38 Update typescript related dependencies to latest
  package-lock.json
  package.json
Labels: internal

#44 Add `main` and `typings` to packages
  packages/athena/package.json
  packages/cache/package.json
  packages/network/package.json
Labels: bug
