Repository data-eden/data-eden, pull requests merged in 2022-06, with the labels that each got.

#10 Only allow importing from the entry point of each package
  packages/athena/package.json
  packages/cache/package.json
  packages/network/package.json
Labels: internal

#18 Add prettier setup to CI
  .github/workflows/ci.yml
  RELEASE.md
  package.json
  packages/athena/__tests__/index-test.ts
  packages/cache/__tests__/index-test.ts
  packages/cache/tsconfig.json
  packages/network/README.md
  packages/network/__tests__/index-test.ts
  packages/network/tsconfig.json
  tsconfig.json
Labels: internal

#12 feat: adds buildFetch functionality to network
  package-lock.json
  packages/network/README.md
  packages/network/__tests__/fetch-test.ts
  packages/network/__tests__/index-test.ts
  packages/network/package.json
  packages/network/src/fetch.ts
  packages/network/src/index.ts
Labels: enhancement

#19 Add eslint <-> TypeScript integration
  .eslintrc.cjs
  package-lock.json
  package.json
  packages/athena/__tests__/index-test.ts
  packages/cache/__tests__/index-test.ts
  packages/network/__tests__/fetch-test.ts
  packages/network/src/fetch.ts
  tsconfig.eslint.json
Labels: internal

#22 Add `npm run lint:fix` setup
  package.json
Labels: internal

#24 Remove `prettier` integration from eslint setup.
  .eslintrc.cjs
  package-lock.json
  package.json
Labels: internal

#23 Setup basic CONTRIBUTING.md.
  CONTRIBUTING.md
  README.md
Labels: documentation, internal

#25 Add simple package.json linting setup
  package-lock.json
  package.json
  packages/athena/package.json
  packages/cache/package.json
  packages/network/package.json
Labels: internal

#29 hjdivad/middlewares with header api
  .eslintrc.cjs
  packages/network/README.md
  packages/network/__tests__/fetch-test.ts
Labels: documentation
