Repository data-eden/data-eden, pull requests merged in 2023-01, with the labels that each got.

#52 Remove `yarn.lock`
  package-lock.json
  yarn.lock
Labels: internal

#51 Add test for middleware ordering (including results)
  packages/network/__tests__/fetch-test.ts
Labels: internal

#50 Update msw to latest
  package-lock.json
  packages/network/__tests__/fetch-test.ts
  packages/network/package.json
Labels: internal

#54 Update `vite` and `vitest` to latest
  package-lock.json
  package.json
  patches/vitest+0.21.1.patch
  tsconfig-base.json
Labels: internal

#55 Replace `msw` with `http` server
  package-lock.json
  packages/network/__tests__/fetch-test.ts
  packages/network/__tests__/utils.ts
  packages/network/package.json
Labels: internal

#45 Require "host" environment to include a `fetch` API
  .github/workflows/ci.yml
  CONTRIBUTING.md
  package-lock.json
  package.json
  packages/network/__tests__/fetch-test.ts
  packages/network/package.json
  packages/network/src/fetch.ts
Labels: breaking

#56 Update typescript related packages to latest.
  package-lock.json
  package.json
Labels: internal

#57 Update linting related packages
  package-lock.json
  package.json
Labels: internal

#60 Improve test performance: Don't wait on `server.close()`
  internal-packages/shared-test-utilities/src/server.ts
Labels: internal

#61 Update release-it dependencies
  package-lock.json
  package.json
Labels: internal

#62 Update vitest + patch-package to latest
  package-lock.json
  package.json
Labels: internal

#64 Ensure changelog can be edited before publishing.
  package.json
Labels: internal

#65 Run `npm install` after the versions are bumped
  package.json
Labels: internal

#66 Ensure that `fetch` is only accessed lazily (allow mocking)
  packages/network/__tests__/fetch-test.ts
  packages/network/src/fetch.ts
Labels: bug

#68 Add script to easily step through `buildFetch` usage.
  .eslintrc.cjs
  dev/simple-fetch-script.js
  internal-packages/shared-test-utilities/package.json
Labels: internal

#69 Expose metadata to middlewares
  packages/network/__tests__/fetch-test.ts
  packages/network/src/fetch.ts
  packages/network/src/index.ts
Labels: enhancement

#82 Remove rollback
  packages/cache/README.md
  packages/cache/__tests__/index-test.ts
  packages/cache/src/cache.ts
Labels: breaking
