Repository data-eden/data-eden, pull requests merged in 2023-07, with the labels that each got.

#173 bug: fix missing fragment docs for gql tags in codegen
  internal-packages/react-graphql-test-app/src/components/DisplayPerson.tsx
  internal-packages/react-graphql-test-app/src/main.tsx
  internal-packages/react-graphql-test-app/src/routes/FetchMore.tsx
  internal-packages/react-graphql-test-app/src/routes/QueryEffect.tsx
  internal-packages/react-graphql-test-app/src/routes/Refetch.tsx
  packages/codegen/__tests__/codegen.test.ts
  packages/codegen/src/gql/output-operations.ts
  packages/network/vite.config.ts
Labels: bug

#174 feat: inlines fragments to simplify use cases and fixes DeepPartial type
  packages/mocker/__tests__/inline-all-fragments.test.ts
  packages/mocker/__tests__/mocker.test.ts
  packages/mocker/src/index.ts
  packages/mocker/src/inline-all-fragments.ts
Labels: bug, enhancement

#176 feat: Support manipulating the promise returned by fetch
  package-lock.json
  packages/network/__tests__/fetch-test.ts
  packages/network/__tests__/settled-tracking-middleware-test.ts
  packages/network/package.json
  packages/network/src/fetch.ts
Labels: enhancement

#175 feat: enable persisted or raw query execution
  internal-packages/react-graphql-test-app/package.json
  internal-packages/react-graphql-test-app/vite.config.ts
  package-lock.json
  package.json
  packages/athena/__tests__/client.test.ts
  packages/athena/src/client.ts
  packages/athena/src/signal-cache.ts
  packages/athena/src/types.ts
  packages/athena/src/utils.ts
  packages/codegen/__tests__/bin.test.ts
  packages/codegen/__tests__/codegen.test.ts
  packages/codegen/src/codegen.ts
  packages/codegen/src/generate-document-files.ts
  packages/codegen/src/gql/output-operations.ts
  packages/codegen/src/index.ts
  packages/codegen/src/types.ts
  packages/ember/package.json
  packages/react/src/use-query.ts
  tsconfig.json
Labels: enhancement, breaking

#178 feat: handle field alias mocking
  packages/mocker/__tests__/__snapshots__/mocker.test.ts.snap
  packages/mocker/__tests__/mocker.test.ts
  packages/mocker/src/index.ts
Labels: enhancement

#181 feat: enable field injection for special cases in codegen
  packages/codegen/__tests__/__snapshots__/codegen.test.ts.snap
  packages/codegen/__tests__/codegen.test.ts
  packages/codegen/src/codegen.ts
  packages/codegen/src/generate-document-files.ts
  packages/codegen/src/gql/extract-definitions.ts
  packages/codegen/src/gql/extractor.ts
  packages/codegen/src/types.ts
  packages/codegen/src/utils.ts
Labels: enhancement

#180 feat: field generators should be able to validate mocked content
  packages/mocker/__tests__/mocker.test.ts
  packages/mocker/src/index.ts
Labels: enhancement
