Repository data-eden/data-eden, pull requests merged in 2023-05, with the labels that each got.

#98 Drop support for Node 14
  .github/workflows/ci.yml
Labels: breaking

#125 chore: multiple fixes to integrate into next application
  package-lock.json
  packages/codegen/README.md
  packages/codegen/__tests__/babel.test.ts
  packages/codegen/__tests__/codegen.test.ts
  packages/codegen/package.json
  packages/codegen/src/babel-plugin.ts
  packages/codegen/src/gql.ts
  packages/codegen/src/gql/foreign-ref-resolver.ts
  packages/codegen/src/gql/output-operations.ts
Labels: bug

#127 [codegen] remove @data-eden/codegen/gql when running babel transform
  packages/codegen/__tests__/babel.test.ts
  packages/codegen/src/babel-plugin.ts
Labels: bug

#137 Ensure that TrackingInfoPerFetch is always shared across all versions.
  packages/network/src/settled-tracking-middleware.ts
Labels: bug

#138 Add a `$debug` property to the `buildFetch` result.
  internal-packages/shared-test-utilities/src/index.ts
  packages/network/__tests__/fetch-test.ts
  packages/network/__tests__/settled-tracking-middleware-test.ts
  packages/network/src/dev.d.ts
  packages/network/src/fetch.ts
  packages/network/src/settled-tracking-middleware.ts
Labels: enhancement
