Repository data-eden/data-eden, pull requests merged in 2023-06, with the labels that each got.

#141 [athena] Fix bug in cycle detection and a few minor tweaks
  internal-packages/graphql-test-server/src/index.ts
  internal-packages/react-graphql-test-app/src/components/DisplayPerson.tsx
  internal-packages/react-graphql-test-app/src/graphql/query-identifiers.json
  internal-packages/react-graphql-test-app/src/main.tsx
  internal-packages/react-graphql-test-app/src/query-identifiers.json
  packages/athena/__tests__/client.test.ts
  packages/athena/__tests__/signal-cache.test.ts
  packages/athena/src/client.ts
  packages/athena/src/signal-cache.ts
  packages/athena/src/types.ts
  packages/ember/tests/dummy/app/network/client.ts
  packages/react/src/provider.ts
Labels: bug, enhancement

#142 [athena] remove duplicate visited check in resolve
  packages/athena/__tests__/client.test.ts
  packages/athena/src/signal-cache.ts
Labels: bug

#147 feat: create mocker with basic support for fragments, queries and mutations
  .eslintignore
  internal-packages/react-graphql-test-app/src/graphql/schema.graphql
  package-lock.json
  packages/mocker/__tests__/mocker.test.ts
  packages/mocker/package.json
  packages/mocker/src/index.ts
  packages/mocker/tsconfig.build.json
  packages/mocker/tsconfig.json
  packages/mocker/vite.config.ts
  tsconfig.json
Labels: enhancement

#153 Add query response caching to Athena
  internal-packages/react-graphql-test-app/src/App.tsx
  internal-packages/react-graphql-test-app/src/aliased/__generated/DisplayPets.graphql.ts
  internal-packages/react-graphql-test-app/src/components/DisplayPerson.tsx
  internal-packages/react-graphql-test-app/src/components/__generated/AddPet.graphql.ts
  internal-packages/react-graphql-test-app/src/components/__generated/DisplayOwner.graphql.ts
  internal-packages/react-graphql-test-app/src/components/__generated/DisplayPerson.graphql.ts
  internal-packages/react-graphql-test-app/src/components/__generated/DisplayPet.graphql.ts
  internal-packages/react-graphql-test-app/src/components/__generated/UpdateCar.graphql.ts
  internal-packages/react-graphql-test-app/src/components/__generated/UpdatePerson.graphql.ts
  internal-packages/react-graphql-test-app/src/components/__generated/UpdatePet.graphql.ts
  internal-packages/react-graphql-test-app/src/graphql/mutations/__generated/CreatePet.graphql.ts
  internal-packages/react-graphql-test-app/src/graphql/mutations/__generated/RemovePet.graphql.ts
  internal-packages/react-graphql-test-app/src/graphql/mutations/__generated/UpdateCar.graphql.ts
  internal-packages/react-graphql-test-app/src/graphql/mutations/__generated/UpdatePerson.graphql.ts
  internal-packages/react-graphql-test-app/src/graphql/mutations/__generated/UpdatePet.graphql.ts
  internal-packages/react-graphql-test-app/src/graphql/queries/__generated/Car.graphql.ts
  internal-packages/react-graphql-test-app/src/graphql/queries/__generated/Person.graphql.ts
  internal-packages/react-graphql-test-app/src/graphql/query-identifiers.json
  internal-packages/react-graphql-test-app/src/main.tsx
  internal-packages/react-graphql-test-app/src/routes/QueryEffect.tsx
  internal-packages/react-graphql-test-app/src/routes/Refetch.tsx
  internal-packages/react-graphql-test-app/src/routes/Unrelated.tsx
  internal-packages/react-graphql-test-app/src/routes/__generated/MutationResult.graphql.ts
  internal-packages/react-graphql-test-app/src/routes/__generated/QueryEffect.graphql.ts
  internal-packages/react-graphql-test-app/src/routes/__generated/Refetch.graphql.ts
  internal-packages/react-graphql-test-app/src/routes/__generated/Unrelated.graphql.ts
  package-lock.json
  packages/athena/__tests__/signal-cache.test.ts
  packages/athena/package.json
  packages/athena/src/client.ts
  packages/athena/src/index.ts
  packages/athena/src/signal-cache.ts
  packages/athena/src/types.ts
  packages/athena/src/utils.ts
  packages/react/src/use-query.ts
Labels: enhancement

#157 chore: fix demo app to make sure it loads
  internal-packages/react-graphql-test-app/package.json
  internal-packages/react-graphql-test-app/vite.config.ts
  package-lock.json
Labels: internal

#159 bug: fix findMore when data at certain levels is undefined when merging
  internal-packages/react-graphql-test-app/src/routes/FetchMore.tsx
  package-lock.json
  packages/react/__tests__/utils.test.ts
  packages/react/package.json
  packages/react/src/use-query.ts
  packages/react/src/utils.ts
  packages/react/vitest.config.ts
Labels: bug

#161 feat: adds mergeResolvers to handle fetchMore data
  internal-packages/graphql-test-server/src/schema.ts
  internal-packages/react-graphql-test-app/src/graphql/query-identifiers.json
  internal-packages/react-graphql-test-app/src/graphql/schema.graphql
  internal-packages/react-graphql-test-app/src/main.tsx
  internal-packages/react-graphql-test-app/src/routes/FetchMore.tsx
  internal-packages/react-graphql-test-app/src/routes/__generated/FetchMore.graphql.ts
  packages/athena/__tests__/signal-cache.test.ts
  packages/athena/src/client.ts
  packages/athena/src/signal-cache.ts
  packages/athena/src/types.ts
  packages/athena/src/utils.ts
  packages/athena/vite.config.ts
  packages/cache/src/cache-revision.ts
  packages/cache/src/cache-transaction.ts
  packages/cache/src/cache.ts
  packages/cache/src/live-transaction.ts
  packages/cache/types/api.d.ts
  packages/react/__tests__/utils.test.ts
  packages/react/package.json
  packages/react/src/use-query.ts
  packages/react/src/utils.ts
  packages/react/vite.config.ts
Labels: enhancement

#162 feat: migrate to typescript@5
  internal-packages/graphql-test-server/package.json
  package-lock.json
  package.json
  packages/codegen/package.json
  packages/ember/package.json
Labels: enhancement

#163 feat: adds __typename to all projections
  packages/codegen/__tests__/codegen.test.ts
  packages/codegen/__tests__/utils.test.ts
  packages/codegen/__tests__/utils/project.ts
  packages/codegen/src/codegen.ts
  packages/codegen/src/generate-document-files.ts
  packages/codegen/src/gql/extractor.ts
  packages/codegen/src/utils.ts
Labels: enhancement

#164 feat: support non-managed entities
  .github/workflows/ci.yml
  internal-packages/react-graphql-test-app/vite.config.ts
  package-lock.json
  packages/athena/.gitignore
  packages/athena/__tests__/client.test.ts
  packages/athena/package.json
  packages/athena/src/client.ts
  packages/athena/src/signal-cache.ts
  packages/athena/src/types.ts
  packages/athena/vitest.config.ts
Labels: enhancement

#167 feat: handle unmanaged objects with synthetic keys
  packages/athena/__tests__/client.test.ts
  packages/athena/__tests__/signal-cache.test.ts
  packages/athena/src/client.ts
  packages/athena/src/signal-cache.ts
  packages/athena/src/types.ts
  packages/athena/src/utils.ts
Labels: bug, enhancement

#168 chore: cleans up design and moves data around
  README.md
  internal-packages/website/docs/intro.md
  internal-packages/website/docs/overview.md
  internal-packages/website/docusaurus.config.js
  internal-packages/website/src/css/custom.css
  internal-packages/website/src/pages/index.js
  internal-packages/website/src/pages/index.module.css
Labels: internal

#169 feat: support union fragments mocking top level
  packages/mocker/__tests__/__snapshots__/mocker.test.ts.snap
  packages/mocker/__tests__/mocker.test.ts
  packages/mocker/src/index.ts
  packages/mocker/vite.config.ts
Labels: bug, enhancement

#170 bug: ensure we build @data-eden/mocker before publishing
  package.json
Labels: bug

#172 feat: make mocker.mock synchronous
  packages/athena/__tests__/client.test.ts
  packages/mocker/README.md
  packages/mocker/__tests__/__snapshots__/mocker.test.ts.snap
  packages/mocker/__tests__/mocker.test.ts
  packages/mocker/src/index.ts
Labels: enhancement
